# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 03:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('richtext', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
