# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_linkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
