# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_linkmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
