# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20160831_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('external_url', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('when', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='testmodel',
        ),
        migrations.DeleteModel(
            name='LinkModel',
        ),
    ]
